services: 
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - "todo-frontend"
      - "todo-backend"
  todo-frontend:
    image: hello-front-dev
    ports:
      - 3000:3000
    build:
      context: ./todo-frontend/
      dockerfile: ./todo-frontend/dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    depends_on:
      - "todo-backend"
  todo-backend:
    image: backend-image
    ports:
      - 3001:3001
    build:
      context: ./todo-backend/
      dockerfile: ./todo-backend/dev.Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app  
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - "mongo"
      - "redis"
  mongo:
     image: mongo
     ports:
       - 27017:27017
     environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: example
       MONGO_INITDB_DATABASE: the_database
     volumes:
       - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
       - mongo_data:/data/db
  redis:
    image: redis
    ports:
      - 6378:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
volumes:
  mongo_data:
  cache:
    driver: local
